### ISSUE TITLE
Introduce safe way to access Result.state-Members directly

### ISSUE THREAD

**Issue by GregOnNet** [seangwright/typescript-functional-extensions#11]
**Is your feature request related to a problem? Please describe.**
Using `getValueOrThrow` or `getErrorOrThrow` is a bit hard to read, even if you have checked before whether the result is in success or error-State.

It would be nice to access `value` and `error` directly, when it is clear in which state the Result is.

**Describe the solution you'd like**
After executing a Type Guard, I want to access `value` or `error` directly.
This should be automatically inferred by the TypeScript Compiler.

**Describe alternatives you've considered**
Currently, I use the existing API for a few weeks by using `*OrThrow()`-Methods.
This approach is not the cleanest.
My Co-Workers being new to this library get confused too. 
They find accessing a value- or error-Object is too complicated.

```ts
if (result.isFailure) {
  throw new RpcException(result.getErrorOrThrow());
}

return result.getValueOrThrow();
```

**Additional context**
- #10

**Comment by seangwright** [comment]
I like the idea of using type guards to let devs access the properties which would throw if not correctly accessed.

I see some monad libraries not allowing direct access at all and instead consumers have to use `.Match(...)`. This is definitely less ergonomic for simple use cases.

**Comment by GregOnNet** [comment]
Maybe there is already a way to accomplish my use case without exposing value and error.

**Use Case**
- In a Controller (HTTP or Messaging)
- If the result is in error state, I want to throw an Error (RPC- / HTTP-Exception)
- If the result is in success state, I want to return the value.

Is there a way of doing this with `match`?
Honestly, I prefer to stay as long as possible with the Monad.

**Comment by seangwright** [comment]
@GregOnNet Here's an example of how to use `Result.match` to achieve what you are trying
https://stackblitz.com/edit/typescript-lhgdur?file=index.ts

You can throw in the failure callback for `match` and the typings will still reflect what is returned in the success callback.

```typescript
const number = r.match({
  success: (n) => n,
  failure: (e) => {
    throw Error(e);
  },
});
```

If I'm working in Angular or Vue, I'll use `Result.tap()` and `Result.tapFailure()` to update state without having to unwrap the value/error. The closure over `this` or the state object works just fine, even with `ResultAsync`.

**Comment by GregOnNet** [comment]
Thanks for the nice write-up @seangwright.

## .match

To me, throwing the error inside the Monad feels like escaping the pattern.
If I just want to access the value, I also need to specify a `success`-Callback.

```ts
const number = r.match({
  success: n => n,
  failure: e => {
    throw Error(e);
  }
});
```

## .tap/.tapFailure

Interesting approach.
The only downside I see here, that I would need to declare a variable and assign it later on.
This could again lead into handling `undefined` values, if I am not mistaken.

```ts
let responseNumber: number | undefined;
let errorMessage: string | undefined;

await apiResult
  .tap(num => {
    responseNumber = num;
  })
  .tapFailure(err => {
    errorMessage = err;
  })
  .toPromise();
```

## How it is solved in CSharpFunctionalExtensions?

CSharpFunctionalExtensions allows accessing `.Value`- and `.Error`-Property. https://github.com/vkhorikov/CSharpFunctionalExtensions#get-rid-of-primitive-obsession.

## Personal conclusion

Comparing all the mentioned approaches, I still believe `Result<T>` will benefit from introducing Type-Guards. 👍
