### ISSUE TITLE
ResultAsync is not flattened in Monad-Chain

### ISSUE THREAD

**Issue by GregOnNet** [seangwright/typescript-functional-extensions#9]
**Describe the bug**
I have a ResultChain that calls a Method returning ResultAsync.
My expectation is, that ResultAsync is transparent for the Chain, but `ResultAsync` is passed to the next operator.

**To Reproduce**

- You can refer to the Example on [StackBlitz](https://stackblitz.com/edit/typescript-j6umbq?file=index.ts&view=editor)

```typescript
class Processor {
  process() {
    this.fetchAnyA()
      .ensure((fetchedA) => !fetchedA, 'Cannot process value already exists')
      .map(() => this.fetchAnyB())
      .map((fetchedB) => this.transformB(fetchedB));
  //            ^ Expected type _any_ but Received _ResultAsync<any>_
  }

  fetchAnyA(): ResultAsync<any> {
    return ResultAsync.from(Promise.reject()).mapError(() => 'Could not load');
  }

  fetchAnyB(): ResultAsync<any> {
    return ResultAsync.from(Promise.reject()).mapError(() => 'Could not load');
  }

  transformB(value: {}) {}
}
```

**UPDATE**

If I use `.bind` instead of `.map` the code works as expected. 🚀  

**Expected behavior**
My expectation is, that ResultAsync is transparent for the Chain, but `ResultAsync` is passed to the next operator.

**Screenshots**
![CleanShot 2022-04-20 at 13 37 41@2x](https://user-images.githubusercontent.com/444278/164223997-fd1ecf14-14fd-4b40-a214-d88a5fc85e32.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 100.0.4896.88 (Official Build) (x86_64)

**Additional context**
I am willing to help to fix this issue if it becomes confirmed as bug.

**Comment by seangwright** [comment]
I believe this is the correct behavior.

Just like with `Result<T>`, `.bind` will flatten the `Result<T>` and `.map` will convert its inner value.

In CSharpFunctionalExtensions, the async `Bind` returns a `Task<Result<T>>`

https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/v2.29.0/CSharpFunctionalExtensions.Tests/ResultTests/Extensions/BindAsyncBothTests.cs#L13

(and here's the definition of [GetResultTask](https://github.com/vkhorikov/CSharpFunctionalExtensions/blob/v2.29.0/CSharpFunctionalExtensions.Tests/ResultTests/Extensions/BindTestsBase.cs#L23))

**Comment by GregOnNet** [comment]
Cool, thanks for the feedback.
I was not ware that `bind` is the flattening-Operation, here. 👍
